CREATE TABLE [dbo].[stay]
(
    [Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
    [structure_id] INT NULL, 
    [title] VARCHAR(MAX) NULL,
    [min_year] INT NULL,
    [max_year] INT NULL,
    [abstract] VARCHAR(MAX) NULL,
    [description] VARCHAR(MAX) NULL,
    [program] VARCHAR(MAX) NULL,
    [created_date] DATETIME2 NULL,
    [view_count] INT NULL,
    [housing] VARCHAR(MAX) NULL, 
    [more_informations] VARCHAR(MAX) NULL, 
    [street] VARCHAR(MAX) NULL, 
    [post_code] VARCHAR(MAX) NULL, 
    [city] VARCHAR(MAX) NULL, 
    [state] VARCHAR(MAX) NULL, 
    [country] VARCHAR(MAX) NULL, 
    [latitude] VARCHAR(MAX) NULL, 
    [longitude] VARCHAR(MAX) NULL, 
    [phone] INT NULL, 
    CONSTRAINT FK_STAY_USER FOREIGN KEY (structure_id) REFERENCES [structure](id)



	-- [Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
    -- [structure_id] INT NULL, 
    -- [name] VARCHAR(MAX) NULL, 
    -- [description] VARCHAR(MAX) NULL, 
    -- [start_date] DATETIME2 NULL, 
    -- [end_date] DATETIME2 NULL,
    -- [abstract] VARCHAR(MAX) NULL, 
    -- [activities] VARCHAR(MAX) NULL, 
    -- [street] VARCHAR(MAX) NULL, 
    -- [city] VARCHAR(MAX) NULL, 
    -- [zip_code] INT NULL, 
    -- [department] VARCHAR(MAX) NULL, 
    -- [region] VARCHAR(MAX) NULL, 
    -- [country] VARCHAR(MAX) NULL, 
    -- [nb_places] INT NULL, 
    -- [other_informations] VARCHAR(MAX) NULL, 
    -- [picture1] VARCHAR(MAX) NULL, 
    -- [picture2] VARCHAR(MAX) NULL, 
    -- [picture3] VARCHAR(MAX) NULL, 
    -- [picture4] VARCHAR(MAX) NULL, 
    -- [picture5] VARCHAR(MAX) NULL, 
    -- [picture6] VARCHAR(MAX) NULL, 
    -- [picture7] VARCHAR(MAX) NULL, 
    -- [price] FLOAT NULL, 
    -- [pratic_level] VARCHAR(MAX) NULL, 
    -- [longitude] FLOAT NULL, 
    -- [latitude] FLOAT NULL, 
    -- [length] INT NULL, 
    -- [nb_view] INT NULL, 
    -- [status] VARCHAR(MAX) NULL,
    -- [new_price] FLOAT NULL,
    -- [min_year] INT NULL, 
    -- [max_year] INT NULL, 
    -- CONSTRAINT FK_STAY_USER FOREIGN KEY (structure_id) REFERENCES [structure](id)

)
